### PR TITLE
Fix summary report bug

### LINKED ISSUE #26: Summary report bug
Upon executing the following command, incorrect values are being generated in the `compare.md` and `compart-time.md` files. These errors are clearly visible in the output. 

```shell
python -m openrlbenchmark.rlops \
    --filters '?we=openrlbenchmark&wpn=cleanrl&ceik=env_id&cen=exp_name&metric=charts/episodic_return' \
        'c51_atari?tag=pr-403' \
    --env-ids BreakoutNoFrameskip-v4 \
    --pc.ncols 1 \
    --pc.ncols-legend 1 \
    --pc.xlabel 'Training Steps' \
    --pc.ylabel 'Episodic Return' \
    --output-filename compare \
    --report
```

Below is a section of the output:

```shell
========= c51_atari?tag=pr-403
collecting runs for BreakoutNoFrameskip-v4
loading <Run openrlbenchmark/cleanrl/1evx4bd4 (finished)> https://wandb.ai/openrlbenchmark/cleanrl/runs/1evx4bd4
loading <Run openrlbenchmark/cleanrl/m1n2osts (finished)> https://wandb.ai/openrlbenchmark/cleanrl/runs/m1n2osts
loading <Run openrlbenchmark/cleanrl/ivre7s6s (finished)> https://wandb.ai/openrlbenchmark/cleanrl/runs/ivre7s6s
openrlbenchmark/cleanrl/c51_atari ({'tag': ['pr-403']}) has 3 runs
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Runtime (m) (mean ± std) ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Environment            ┃ openrlbenchmark/cleanrl/c51_atari ({'tag': ['pr-403']}) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ BreakoutNoFrameskip-v4 │ 173.0452340770474                                       │
└────────────────────────┴─────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Episodic Return (mean ± std) ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Environment            ┃ openrlbenchmark/cleanrl/c51_atari ({'tag': ['pr-403']}) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ BreakoutNoFrameskip-v4 │ 172.98 ± 16.96                                          │
└────────────────────────┴─────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Runtime (m) Average ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Environment                                             ┃ Average Runtime   ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ openrlbenchmark/cleanrl/c51_atari ({'tag': ['pr-403']}) │ 173.0452340770474 │
└─────────────────────────────────────────────────────────┴───────────────────┘
```

The expected output should look like this:

```shell
========= c51_atari?tag=pr-403
collecting runs for BreakoutNoFrameskip-v4
loading <Run openrlbenchmark/cleanrl/1evx4bd4 (finished)> https://wandb.ai/openrlbenchmark/cleanrl/runs/1evx4bd4
loading <Run openrlbenchmark/cleanrl/m1n2osts (finished)> https://wandb.ai/openrlbenchmark/cleanrl/runs/m1n2osts
loading <Run openrlbenchmark/cleanrl/ivre7s6s (finished)> https://wandb.ai/openrlbenchmark/cleanrl/runs/ivre7s6s
openrlbenchmark/cleanrl/c51_atari ({'tag': ['pr-403']}) has 3 runs
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Runtime (m) (mean ± std) ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Environment            ┃ openrlbenchmark/cleanrl/c51_atari ({'tag': ['pr-403']}) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ BreakoutNoFrameskip-v4 │ 321.4837614001609                                       │
└────────────────────────┴─────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Episodic Return (mean ± std) ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Environment            ┃ openrlbenchmark/cleanrl/c51_atari ({'tag': ['pr-403']}) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ BreakoutNoFrameskip-v4 │ 446.07 ± 3.42                                           │
└────────────────────────┴─────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Runtime (m) Average ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Environment                                             ┃ Average Runtime   ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ openrlbenchmark/cleanrl/c51_atari ({'tag': ['pr-403']}) │ 321.4837614001609 │
└─────────────────────────────────────────────────────────┴───────────────────┘
```

---

You can naturally view the code here:

https://github.com/openrlbenchmark/openrlbenchmark/blob/8f41aedccd3cb92410176936885b668d78a918d0/openrlbenchmark/rlops.py#L240

After examining the issue, I believe there are two underlying causes.

1. The key problem appears to be the fact that the `run.history` function does not sort data by `global_step`, so we need to sort it.
2. It's not enough to just sample 1500 samples with `run.history`, because many of those 1500 samples do not contain the data we need. After my tests, I found that fewer than 100 of these samples contained useful information. We take the average of the last `metric_last_n_average_window` samples of this less than 100 samples is not enough. Therefore, I suggest the following two potential solutions:
    1. `run.history(samples=15000)` Increase the number of samples so that the most complete data is retained, but the number of samples may need to be adjusted according to the report density of `episodic_return` in the experiment.
    2. `run_df = run.history(samples=1500, keys=["global_step", "_runtime", "charts/episodic_return", runset.metric])` Only sample the data we need, but this may lose some columns that we may need later.

### PR DESCRIPTION
**Pull request by sdpkjc**
Fixes #26

### CODE REVIEW

**Review by vwxyzjn — APPROVED** [review]
The change looks good to me! Could you add the change to other variants as well? Then feel free to merge.

**Comment by sdpkjc** [comment]
I have applied the same changes to other versions as well. I apologize for not having the permissions to run CI and merge the PR. I kindly request that you review and merge those as well. Once again, thank you for taking the time to review and support my work!

**Comment by vwxyzjn** [comment]
Thanks for creating the PR and sorry, I didn’t realize I need to approve the workflow earlier. I have just invited you to the repository as a collaborator, so your workflow should automatically run now.

**Comment by sdpkjc** [comment]
Considering the GitHub security policy, secrets are not passed to the runner when a workflow runs on a forked repository.    Due to this, I had to test it on my forked repository. I have attached a screenshot of the successful test results.

image

There are a few other bugs in `rlops_multi_metrics.py` that I can't test to see if the current changes are working, but that I'd like to fix in #25.

**Pull request merged**
