### PR TITLE
Update CITATION.cff

### PR DESCRIPTION
**Pull request by qgallouedec**
Hi, really sorry for the duplicates, but I don't know if the email I've sent reached everyone, I'll ping you here:

Open RL Benchmark will be the subject of a scientific paper, and your name (unless you disagree) will be listed as an author.
I need you to provide me with your affiliation(s) as you would like it to appear in the paper. I need this information promptly, and if not provided, I will do my best based on the information I can find on your LinkedIn, GitHub, personal website, etc.

You can reply here, send me a DM, reply on discord, send me a carrier pigeon, anything is fine with me.

I need the affiliation(s) for:
- [x] Shengyi Huang
- [x] Quentin Gallouédec
- [x] Florian Felten
- [x] Antonin Raffin
- [x] Rousslan Fernand Julien Dossa (@dosssman)
- [x] Yanxiao Zhao
- [x] Ryan Sullivan (@RyanNavillus)
- [x] Viktor Makoviychuk (@@ViktorM)
- [x] Denys Makoviichuk
- [x] Mohamad H. Danesh
- [x] Cyril Roumégous (@croumegous)
- [x] Jiayi Weng
- [ ] Chufan Chen (@ChufanSuki)
- [x] Md Masudur Rahman
- [x] João G. M. Araújo
- [x] Guorui Quan (@quangr)
- [x] Daniel Tan
- [x] Timo Klein
- [x] Rujikorn Charakorn (@51616)
- [x] Mark Towers (@pseudo-rnd-thoughts)
- [x] Yann Berthelot (@YannBerthelot)
- [x] Kinal Mehta
- [x] Dipam Chakraborty (@dipamc)
- [x] Arjun KG (@arjun-kg)
- [x] Valentin Charraut (@charraut)
- [x] Chang Ye (@yooceii)
- [x] Zichen Liu (@lkevinzc)
- [x] Lucas N. Alegre
- [x] Alexander Nikulin (@Howuhh)
- [x] Xiao Hu (@young-geng)
- [x] Tianlin Liu (@liutianlin0121)
- [x] Jongwook Choi
- [x] Brent Yi (@brentyi)

### CODE REVIEW

**Comment by liutianlin0121** [comment]
Thanks for including me as an author! My affiliation: Tianlin Liu, University of Basel.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, my affiliation is University of Southampton

**Comment by lkevinzc** [comment]
Thank you! My affiliation: Zichen Liu, Sea AI Lab.

**Comment by charraut** [comment]
Thank for you including me! My affiliation is Valentin Charraut, Valeo Driving Assistance Research

**Comment by dipamc** [comment]
Thanks @vwxyzjn. My affiliation is AIcrowd SA

**Comment by ViktorM** [comment]
Hi Quentin,

I already replied to another email. My affiliation is NVIDIA. Thank you!


Best,
Viktor

**Comment by ffelten** [comment]
@qgallouedec don't forget to update the bibtex in the README too :-)

**Comment by qgallouedec** [comment]
> @qgallouedec don't forget to update the bibtex in the README too :-)

Thanks!

**Comment by chufanchen** [comment]
Thanks for adding me. My affiliation is Zhejiang University.

**Pull request merged**
